### ISSUE TITLE
Artifact checklist

### ISSUE THREAD

**Issue by samth** [rjnw/hakaru-benchmarks#1]
- [x] Targets for exact inference benchmarks
- [x] Explain the provenance of test data (both downloaded and randomly generated) in README-ARTIFACT.md
- [x] Turn off “Automatic Screen Lock” under Settings->Privacy and set “Power Saving, Blank Screen” to “Never” under Settings->Power
- [x] sudo apt-get install fonts-linuxlibertine
- [x] ln -s ~/hakaru-benchmarks/README-ARTIFACT.md ~
- [x] Upload final image with finished edits of README-ARTIFACT.md and latest hakaru repository (with May 14 commit)
- [x] Submit artifact (VM image + also README-ARTIFACT.md outside)
- [ ] Save our actual benchmark results somewhere archival
